### ISSUE TITLE
Similarity to Racker?

### ISSUE THREAD

**Issue by mrjcleaver** [ianchesal/packer-config#21]
Per https://github.com/mitchellh/packer/pull/3860/files I'm wondering how different packer-config is to https://github.com/aspring/racker. Any thoughts?

Thanks,
   Martin.

**Comment by ianchesal** [comment]
Similar but different. One big thing that stands out is I didn't write Racker. :)

packer-config has a standard Ruby object interface for working with Packer. It doesn't have a strongly-opinionated DSL. That seems to be the big difference. Otherwise they aim to solve the same problem: working with Packer configuration files on a large scale can be unwieldy because it's not a fully-formed programming language.

**Comment by mrjcleaver** [comment]
Doesn't Packer use Go? While the `{{` syntax makes my eyes hurt (and Packer seems to have no means to DRY our repeated constant definitions), it is fair to call it (Go) not a fully-formed language?

**Comment by ianchesal** [comment]
While Packer the program is written in Go, it's template file format is its own DSL which is a custom extension of the JSON format.

See: https://github.com/mitchellh/packer/blob/master/template/parse.go
